name: build-cloudflared-android-arm32

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Clone source
        run: |
          git clone https://github.com/cloudflare/cloudflared.git

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22

      - name: Install NDK
        run: |
          wget https://dl.google.com/android/repository/android-ndk-r26d-linux.zip
          unzip android-ndk-r26d-linux.zip

      - name: Build Android ARM32
        run: |
          export NDK=$PWD/android-ndk-r26d
          export TOOLCHAIN=$NDK/toolchains/llvm/prebuilt/linux-x86_64

          export CC=$TOOLCHAIN/bin/armv7a-linux-androideabi21-clang
          export CXX=$TOOLCHAIN/bin/armv7a-linux-androideabi21-clang++

          cd cloudflared/cmd/cloudflared

          CGO_ENABLED=1 \
          GOOS=android \
          GOARCH=arm \
          GOARM=7 \
          CC=$CC \
          CXX=$CXX \
          go build -o cloudflared-android-arm
          
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: cloudflared-android-arm
          path: cloudflared/cmd/cloudflared/cloudflared-android-arm
